/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Utkarsh Tiwari (UT | utk09)",
  "tagline": "FRONTEND DEVELOPER | DATA ENGINEER | ASPIRING FULLSTACK DEVELOPER",
  "favicon": "img/favicon.ico?v=4",
  "url": "https://utk09.com",
  "baseUrl": "/",
  "organizationName": "utk09",
  "projectName": "utk09.github.io",
  "onBrokenLinks": "throw",
  "markdown": {
    "hooks": {
      "onBrokenMarkdownLinks": "warn",
      "onBrokenMarkdownImages": "throw"
    },
    "format": "mdx",
    "mermaid": false,
    "emoji": true,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    }
  },
  "onDuplicateRoutes": "warn",
  "trailingSlash": false,
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "presets": [
    [
      "classic",
      {
        "sitemap": {
          "changefreq": "weekly",
          "priority": 0.9,
          "filename": "sitemap.xml"
        },
        "gtag": {
          "trackingID": [
            "G-67H9CP0Z8Q",
            "G-H98RBFSDQ5"
          ]
        },
        "docs": {
          "sidebarPath": "./sidebars.ts",
          "routeBasePath": "/tutorials",
          "sidebarCollapsible": true,
          "path": "tutorials"
        },
        "blog": {
          "routeBasePath": "/blogs",
          "showReadingTime": true,
          "postsPerPage": 5,
          "blogSidebarCount": "ALL",
          "blogSidebarTitle": "All Posts",
          "feedOptions": {
            "type": [
              "rss",
              "atom"
            ],
            "title": "Utkarsh Tiwari (UT) Blog",
            "description": "Tech tutorials, insights, and developer experiences from Utkarsh Tiwari",
            "copyright": "Copyright 2026 Utkarsh Tiwari",
            "language": "en"
          }
        },
        "theme": {
          "customCss": "./src/css/custom.css"
        }
      }
    ]
  ],
  "plugins": [
    null
  ],
  "headTags": [
    {
      "tagName": "script",
      "attributes": {
        "type": "application/ld+json"
      },
      "innerHTML": "{\"@context\":\"https://schema.org\",\"@type\":\"Person\",\"name\":\"Utkarsh Tiwari\",\"alternateName\":\"UT\",\"url\":\"https://utk09.com\",\"image\":\"https://utk09.com/img/ut_portrait_image.png\",\"sameAs\":[\"https://github.com/utk09\",\"https://www.linkedin.com/in/utkarsh09/\",\"https://twitter.com/utk0909\",\"https://dev.to/utk09\",\"https://medium.com/@utk09\"],\"jobTitle\":\"FX UI Developer (AVP)\",\"worksFor\":{\"@type\":\"Organization\",\"name\":\"Barclays\"}}"
    }
  ],
  "themeConfig": {
    "metadata": [
      {
        "name": "description",
        "content": "Frontend Developer | Blogger | Major League Hacking (MLH) Coach | Data Engineer | YouTuber @TuplesEdu | MLH Technical Program Associate | Software Engineer"
      },
      {
        "name": "keywords",
        "content": "utkarsh tiwari, UT, utk09, TuplesEdu, Major League Hacking, MLH, youtuber, frontend development, data engineering, software engineering, tech blogging, technology, lifelong learning"
      },
      {
        "name": "author",
        "content": "Utkarsh Tiwari (UT | utk09)"
      },
      {
        "name": "robots",
        "content": "index, follow"
      },
      {
        "property": "og:type",
        "content": "website"
      },
      {
        "property": "og:site_name",
        "content": "Utkarsh Tiwari (UT)"
      },
      {
        "property": "og:locale",
        "content": "en_US"
      },
      {
        "name": "twitter:card",
        "content": "summary_large_image"
      },
      {
        "name": "twitter:site",
        "content": "@utk0909"
      },
      {
        "name": "twitter:creator",
        "content": "@utk0909"
      }
    ],
    "colorMode": {
      "defaultMode": "dark",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "image": "img/logo.png?v=4",
    "navbar": {
      "title": "UT",
      "logo": {
        "alt": "Utkarsh Tiwari (UT) Logo",
        "src": "img/logo.png?v=4"
      },
      "items": [
        {
          "type": "docSidebar",
          "sidebarId": "tutorialSidebar",
          "position": "left",
          "label": "Tutorials"
        },
        {
          "to": "/blogs",
          "label": "Blogs",
          "position": "left"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "light",
      "links": [
        {
          "title": "About",
          "items": [
            {
              "label": "Tutorials",
              "to": "/tutorials"
            },
            {
              "label": "Blogs",
              "to": "/blogs"
            },
            {
              "label": "Resume",
              "to": "/resume"
            }
          ]
        },
        {
          "title": "Social",
          "items": [
            {
              "label": "LinkedIn",
              "href": "https://www.linkedin.com/in/utkarsh09/"
            },
            {
              "label": "Twitter",
              "href": "https://twitter.com/utk0909"
            },
            {
              "label": "GitHub",
              "href": "https://github.com/utk09"
            }
          ]
        },
        {
          "title": "External",
          "items": [
            {
              "label": "Dev.to",
              "href": "https://dev.to/utk09"
            },
            {
              "label": "Medium",
              "href": "https://medium.com/@utk09"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2026 Utkarsh Tiwari (UT | utk09). Built with &hearts; using Docusaurus."
    },
    "docs": {
      "sidebar": {
        "hideable": true,
        "autoCollapseCategories": false
      },
      "versionPersistence": "localStorage"
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "future": {
    "v4": {
      "removeLegacyPostBuildHeadAttribute": false,
      "useCssCascadeLayers": false
    },
    "experimental_faster": {
      "swcJsLoader": false,
      "swcJsMinimizer": false,
      "swcHtmlMinimizer": false,
      "lightningCssMinimizer": false,
      "mdxCrossCompilerCache": false,
      "rspackBundler": false,
      "rspackPersistentCache": false,
      "ssgWorkerThreads": false
    },
    "experimental_storage": {
      "type": "localStorage",
      "namespace": false
    },
    "experimental_router": "browser"
  },
  "onBrokenAnchors": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "themes": [],
  "scripts": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false
};
